export  const  REQUEST_COLUMNS = 'REQUEST_COLUMNS';
export  const  REQUEST_COLUMNS_SUCCESS = 'REQUEST_COLUMNS_SUCCESS';
export  const  REQUEST_COLUMNS_FAILED = 'REQUEST_COLUMNS_FAILED';

export const REQUEST_DATA = "REQUEST_DATA";
export const REQUEST_DATA_SUCCESS = "REQUEST_DATA_SUCCESS";
export const REQUEST_DATA_FAIL = "REQUEST_DATA_FAIL";