export  const  REQUEST_COLUMNS = 'REQUEST_COLUMNS';
export  const  REQUEST_COLUMNS_SUCCESS = 'REQUEST_COLUMNS_SUCCESS';
export  const  REQUEST_COLUMNS_FAILED = 'REQUEST_COLUMNS_FAILED';

export const REQUEST_DATA = "REQUEST_DATA";
export const REQUEST_DATA_SUCCESS = "REQUEST_DATA_SUCCESS";
export const REQUEST_DATA_FAIL = "REQUEST_DATA_FAIL";

export const COLUMN_DRAGGED = "COLUMN_DRAGGED";
export const ITEM_DELETED = "ITEM_DELETED";
export const ALL_ITEMS_DELETED = "ALL_ITEMS_DELETED";